// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/firstbrief-header/HeaderExploration.tsx": () => import("../components/mockups/firstbrief-header/HeaderExploration.tsx")
};
